"""Deliver the digest via email.

Uses SMTP directly. For Gmail, you'll need an App Password
(not your regular password). See:
https://support.google.com/accounts/answer/185833
"""

from __future__ import annotations

import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText


def send_digest_email(digest_html: str, config: dict) -> None:
    """Send the digest as an HTML email."""
    delivery = config["delivery"]
    smtp_cfg = delivery["smtp"]
    today = datetime.now().strftime("%B %d, %Y")

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"Your Daily Digest — {today}"
    msg["From"] = delivery["from_address"]
    msg["To"] = delivery["to_address"]

    # Wrap the digest HTML in a basic email template
    full_html = f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
             max-width: 640px; margin: 0 auto; padding: 20px;
             color: #1a1a1a; line-height: 1.6;">
{digest_html}
<hr style="margin-top: 32px; border: none; border-top: 1px solid #ddd;">
<p style="font-size: 12px; color: #888;">
  Generated by your Daily Digest agent.
  <a href="https://github.com/you/daily-digest">Edit your config</a> to tune.
</p>
</body>
</html>"""

    # Plain text fallback (strip tags, good enough)
    import re
    plain = re.sub(r"<[^>]+>", "", full_html)

    msg.attach(MIMEText(plain, "plain"))
    msg.attach(MIMEText(full_html, "html"))

    print(f"  Sending to {delivery['to_address']}...")
    with smtplib.SMTP(smtp_cfg["host"], smtp_cfg["port"]) as server:
        server.starttls()
        server.login(smtp_cfg["username"], smtp_cfg["password"])
        server.send_message(msg)
    print("  ✓ Sent!")
