"""Render selected items into an HTML email digest."""

from __future__ import annotations

from datetime import datetime
from typing import Any

from agent.models import ContentItem

ACTION_META = {
    "read_in_depth": {"emoji": "\U0001f4d6", "heading": "Read In Depth", "color": "#1a73e8"},
    "check_it_out": {"emoji": "\U0001f3ac", "heading": "Check It Out", "color": "#e8710a"},
    "fyi": {"emoji": "\u26a1", "heading": "FYI", "color": "#5f6368"},
}

ACTION_ORDER = ["read_in_depth", "check_it_out", "fyi"]


def format_digest(items: list[ContentItem], config: dict[str, Any]) -> tuple[str, str]:
    """Return (subject_line, html_body) for the email digest."""
    today = datetime.now().strftime("%A, %B %-d")
    subject = f"Your Morning Digest \u2014 {today}"

    grouped: dict[str, list[ContentItem]] = {k: [] for k in ACTION_ORDER}
    for item in items:
        bucket = item.action_type if item.action_type in grouped else "fyi"
        grouped[bucket].append(item)

    sections_html = ""
    for action_type in ACTION_ORDER:
        group = grouped[action_type]
        if not group:
            continue
        meta = ACTION_META[action_type]
        items_html = ""
        for item in group:
            title_href = item.discussion_url if item.discussion_url else item.url
            items_html += f"""\
            <tr><td style="padding:12px 0;border-bottom:1px solid #eee;">
              <a href="{title_href}" style="color:#1a1a1a;text-decoration:none;font-weight:600;font-size:15px;">{item.title}</a><br/>
              <span style="color:#444;font-size:14px;line-height:1.5;">{item.summary}</span><br/>
              <span style="color:#888;font-size:13px;">{item.source}</span>
            </td></tr>
"""
        sections_html += f"""\
        <tr><td style="padding:20px 0 8px 0;">
          <span style="font-size:18px;font-weight:700;color:{meta['color']};">{meta['emoji']} {meta['heading']}</span>
        </td></tr>
        {items_html}
"""

    html = f"""\
<!DOCTYPE html>
<html><head><meta charset="utf-8"/></head>
<body style="margin:0;padding:0;background:#f5f5f5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#f5f5f5;"><tr><td align="center" style="padding:24px 16px;">
<table width="600" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:8px;overflow:hidden;">
  <tr><td style="background:#1a1a1a;padding:24px 28px;">
    <span style="color:#fff;font-size:22px;font-weight:700;">Morning Digest</span><br/>
    <span style="color:#aaa;font-size:14px;">{today} &middot; ~5 min read</span>
  </td></tr>
  <tr><td style="padding:8px 28px 28px 28px;">
    <table width="100%" cellpadding="0" cellspacing="0">{sections_html}</table>
  </td></tr>
  <tr><td style="background:#fafafa;padding:16px 28px;border-top:1px solid #eee;">
    <span style="color:#999;font-size:12px;">Generated by Daily Digest &middot; Powered by your config, not an algorithm</span>
  </td></tr>
</table>
</td></tr></table>
</body></html>
"""
    return subject, html
